import type { ActivityEntry, Opportunity, RawSignal } from './types'

/**
 * Seeded sample data — fictional but realistic. In production these rows
 * arrive from the intake feeds (planning data, RFP portals, award notices,
 * news monitoring, CSV import, pasted URLs) and are triaged by the AI
 * classifier before human review.
 */
export const SEED_SIGNALS: RawSignal[] = [
  // ── London ─────────────────────────────────────────────────────────
  {
    id: 'SIG-1041',
    title: 'Pre-app filed: refurbishment of 1990s office, Gresham Street EC2',
    city: 'London',
    district: 'City of London',
    sectorGuess: 'Office',
    subSectorGuess: 'Office retrofit',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.cityoflondon.gov.uk/26-00871-PREAPP',
    rawSummary:
      'Pre-application advice request for "refurbishment, rooftop extension and reconfiguration" of an 11,400 m² 1990s office. Filed by a planning consultant; no architect named. Single tenancy reported to expire 2027.',
    dateFound: '2026-07-06',
    aiStatus: 'Auto-classified',
    aiNote: 'Retrofit intent confirmed, no design team attached — strongest pre-procurement pattern.',
    reviewStatus: 'Needs review',
    confidence: 4,
  },
  {
    id: 'SIG-1038',
    title: 'S73 amendment: hotel element switched to co-living, Filmworks Ealing',
    city: 'London',
    district: 'Ealing',
    sectorGuess: 'Living',
    subSectorGuess: 'Co-living',
    sourceType: 'Planning',
    sourceLink: 'https://pam.example.ealing.gov.uk/263012VAR',
    rawSummary:
      'Section 73 application converting a consented 140-key hotel to 188 co-living units. Operator "Habitat & Co" named in the planning statement for the first time.',
    dateFound: '2026-07-03',
    aiStatus: 'Auto-classified',
    aiNote: 'New operator entering a consented scheme — possible delivery-architect procurement.',
    reviewStatus: 'Unreviewed',
    confidence: 3,
  },
  {
    id: 'SIG-1035',
    title: 'Full application: 28-storey BTR tower, Nine Elms plot C',
    city: 'London',
    district: 'Wandsworth',
    sectorGuess: 'Living',
    subSectorGuess: 'BTR',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.wandsworth.gov.uk/2026-2214-FUL',
    rawSummary:
      '412-home BTR application submitted with a full design team already appointed. Applicant Riverline Living; decision expected Q4 2026.',
    dateFound: '2026-07-01',
    aiStatus: 'Auto-classified',
    aiNote: 'Design team already in place — value is competitor and buyer intelligence, not a direct lead.',
    reviewStatus: 'Unreviewed',
    confidence: 4,
  },
  {
    id: 'SIG-1029',
    title: 'Manual note: former client now Director of Estates, south London university',
    city: 'London',
    district: 'Southwark',
    sectorGuess: 'Living',
    subSectorGuess: 'Student accommodation',
    sourceType: 'Manual intelligence',
    sourceLink: 'https://example.internal/crm/contact-4471',
    rawSummary:
      'JM met a former workplace client, now Director of Estates at a south London university. Mentioned a condition-driven halls refurbishment backlog and a stalled residences masterplan.',
    dateFound: '2026-06-26',
    aiStatus: 'Manual entry',
    aiNote: 'Relationship intelligence — logged manually, no automated source.',
    reviewStatus: 'Needs review',
    confidence: 4,
  },
  {
    id: 'SIG-1022',
    title: 'Prior approval: office-to-resi PD conversion, Croydon',
    city: 'London',
    district: 'Croydon',
    sectorGuess: 'Living',
    subSectorGuess: 'Office-to-living',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.croydon.gov.uk/26-01633-GPDO',
    rawSummary:
      'Prior approval sought for PD conversion of a 2,100 m² 1980s office to 34 flats. Applicant is a small regional converter using a repeat delivery team.',
    dateFound: '2026-06-22',
    aiStatus: 'Auto-classified',
    aiNote: 'PD route, small scale, incumbent team — low fee potential and no design mandate.',
    reviewStatus: 'Ignored',
    confidence: 3,
  },
  {
    id: 'SIG-1044',
    title: 'CSV import: Bloomsbury hotel marketed for alternative use',
    city: 'London',
    district: 'Camden',
    sectorGuess: 'Living',
    subSectorGuess: 'Hotel-to-living',
    sourceType: 'CSV import',
    sourceLink: 'https://example-agency.co.uk/particulars/bloomsbury-hotel-2026',
    rawSummary:
      'Imported from the weekly agency-particulars CSV: 190-key 1970s hotel marketed with "potential for alternative uses including student and co-living, subject to planning".',
    dateFound: '2026-07-07',
    aiStatus: 'Auto-classified',
    aiNote: 'Marketing language signals owner intent; conversion feasibility is the natural first commission.',
    reviewStatus: 'Unreviewed',
    confidence: 3,
  },
  {
    id: 'SIG-1027',
    title: 'Refused at committee: 34-storey co-living tower, Stratford High Street',
    city: 'London',
    district: 'Newham',
    sectorGuess: 'Living',
    subSectorGuess: 'Co-living',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.newham.gov.uk/26-00544-FUL',
    rawSummary:
      '702-unit co-living tower refused at committee against officer recommendation — massing, wind and ground-floor deadening cited. Applicant Skyfield Living weighing appeal versus redesign.',
    dateFound: '2026-06-24',
    aiStatus: 'Auto-classified',
    aiNote: 'Refusal against officer advice — use principle intact, design not. Classic redesign opening.',
    reviewStatus: 'Convert to opportunity',
    confidence: 4,
    linkedOpportunityId: 'OPP-2007',
  },
  // ── Birmingham ─────────────────────────────────────────────────────
  {
    id: 'SIG-1031',
    title: 'Refused: 480-bed PBSA scheme, Digbeth High Street',
    city: 'Birmingham',
    district: 'Digbeth',
    sectorGuess: 'Living',
    subSectorGuess: 'PBSA',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.birmingham.gov.uk/2026-02981-PA',
    rawSummary:
      'PBSA scheme refused on heritage-edge massing and amenity grounds; officers supported the principle of student use. Applicant Northgate Student Living has 12 weeks to appeal.',
    dateFound: '2026-06-29',
    aiStatus: 'Auto-classified',
    aiNote: 'Refusal with use principle supported — redesign-to-consent route scores well.',
    reviewStatus: 'Needs review',
    confidence: 4,
  },
  {
    id: 'SIG-1018',
    title: 'Regeneration prospectus: Eastside growth framework 2026',
    city: 'Birmingham',
    district: 'Eastside',
    sectorGuess: 'Living',
    subSectorGuess: 'Mixed-use living',
    sourceType: 'Regeneration prospectus',
    sourceLink: 'https://example-regen.birmingham.gov.uk/eastside-framework-2026',
    rawSummary:
      'New growth framework identifies four living-led plots around the HS2 curzon approach, with soft market testing signalled for early 2027.',
    dateFound: '2026-06-17',
    aiStatus: 'Auto-classified',
    aiNote: 'Prospectus-stage — a full cycle ahead of procurement; positioning value only.',
    reviewStatus: 'Unreviewed',
    confidence: 3,
  },
  {
    id: 'SIG-1046',
    title: 'Market article: "Fringe offices face the 2030 EPC cliff" — Birmingham focus',
    city: 'Birmingham',
    district: 'Jewellery Quarter',
    sectorGuess: 'Office',
    subSectorGuess: 'Stranded office asset',
    sourceType: 'Market article',
    sourceLink: 'https://example-propertyweek.co.uk/birmingham-epc-cliff-2026',
    rawSummary:
      'Trade-press analysis naming three Jewellery Quarter office holdings as sub-EPC-C with leases rolling 2027–28 and no published retrofit plans.',
    dateFound: '2026-07-07',
    aiStatus: 'Auto-classified',
    aiNote: 'Named assets + compliance deadline — candidate list for a retrofit-cluster approach.',
    reviewStatus: 'Unreviewed',
    confidence: 2,
  },
  {
    id: 'SIG-1025',
    title: 'Contract award: cost consultant appointed for Snow Hill wing retrofit',
    city: 'Birmingham',
    district: 'Snow Hill',
    sectorGuess: 'Office',
    subSectorGuess: 'Office retrofit',
    sourceType: 'Contract award',
    sourceLink: 'https://www.find-tender.example.gov.uk/notice/snow-hill-qs-2026',
    rawSummary:
      'Award notice: QS services for a phased retrofit of the Snow Hill wing, ~14,000 m². Architect appointment expected to follow within two quarters.',
    dateFound: '2026-06-23',
    aiStatus: 'Auto-classified',
    aiNote: 'Buyer active — design services likely next in the procurement sequence.',
    reviewStatus: 'Watch',
    confidence: 3,
  },
  // ── Manchester ─────────────────────────────────────────────────────
  {
    id: 'SIG-1039',
    title: 'RFP: Manchester City Council civic office estate strategy',
    city: 'Manchester',
    district: 'City Centre',
    sectorGuess: 'Office',
    subSectorGuess: 'Office retrofit',
    sourceType: 'RFP',
    sourceLink: 'https://procontract.example.gov.uk/manchester/MCC-2026-EST-021',
    rawSummary:
      'Open tender for multidisciplinary estate strategy: rationalisation, retrofit and net-zero pathway across six civic office buildings. Deadline 31 Jul 2026; quality-weighted 60/40.',
    dateFound: '2026-07-04',
    aiStatus: 'Auto-classified',
    aiNote: 'Live matched tender — hard deadline; bid/no-bid decision needed this week.',
    reviewStatus: 'Needs review',
    confidence: 5,
  },
  {
    id: 'SIG-1033',
    title: 'Stalled: 600-bed PBSA in third amendment round, First Street',
    city: 'Manchester',
    district: 'First Street',
    sectorGuess: 'Living',
    subSectorGuess: 'PBSA',
    sourceType: 'Planning',
    sourceLink: 'https://pa.example.manchester.gov.uk/139442-FO-2025',
    rawSummary:
      'PBSA application in amendment cycles for 13 months; third revision trims two storeys after daylight objections. Viability statement re-submitted twice.',
    dateFound: '2026-06-30',
    aiStatus: 'Auto-classified',
    aiNote: 'Three amendment rounds — the pattern that precedes withdrawal or a design-team change.',
    reviewStatus: 'Needs review',
    confidence: 3,
  },
  {
    id: 'SIG-1042',
    title: 'Developer signal: Vela Living acquires Castlefield canal-side site',
    city: 'Manchester',
    district: 'Castlefield',
    sectorGuess: 'Living',
    subSectorGuess: 'BTR',
    sourceType: 'Company/developer signal',
    sourceLink: 'https://example-placenorthwest.co.uk/vela-castlefield-2026',
    rawSummary:
      'Vela Living completes on a 1.1-acre canal-side site with lapsed 2019 consent for 280 homes. Statement says it will "review the consented scheme against current standards".',
    dateFound: '2026-07-06',
    aiStatus: 'Auto-classified',
    aiNote: 'Lapsed consent + new owner reviewing design — feasibility architect likely to be procured.',
    reviewStatus: 'Unreviewed',
    confidence: 3,
  },
  {
    id: 'SIG-1036',
    title: 'RFP: north-west universities halls refurbishment framework',
    city: 'Manchester',
    district: '—',
    sectorGuess: 'Living',
    subSectorGuess: 'Student accommodation',
    sourceType: 'RFP',
    sourceLink: 'https://www.find-tender.example.gov.uk/notice/nw-halls-framework-2026',
    rawSummary:
      'Four-year design-services framework for halls refurbishment and densification feasibility across three NW universities. PQQ deadline 21 Aug 2026.',
    dateFound: '2026-07-02',
    aiStatus: 'Auto-classified',
    aiNote: 'Framework seat — converts sector BD into a call-off pipeline; PQQ runway adequate.',
    reviewStatus: 'Needs review',
    confidence: 5,
  },
  {
    id: 'SIG-1020',
    title: 'Market article: Albert Bridge House campus sale completes',
    city: 'Manchester',
    district: 'City Centre',
    sectorGuess: 'Office',
    subSectorGuess: 'Office repositioning',
    sourceType: 'Market article',
    sourceLink: 'https://example-placenorthwest.co.uk/albert-bridge-house-sale',
    rawSummary:
      'Bridgewater Real Estate completes purchase of the 1960s Albert Bridge House campus, citing "comprehensive repositioning" plans. No design team named in coverage.',
    dateFound: '2026-06-18',
    aiStatus: 'Auto-classified',
    aiNote: 'Repositioning stated on the record, team unnamed — direct approach window open.',
    reviewStatus: 'Convert to opportunity',
    confidence: 3,
    linkedOpportunityId: 'OPP-2002',
  },
  // ── Bristol ────────────────────────────────────────────────────────
  {
    id: 'SIG-1030',
    title: 'Contract award: development partner selected for Broadmead blocks',
    city: 'Bristol',
    district: 'Broadmead',
    sectorGuess: 'Office',
    subSectorGuess: 'Commercial mixed-use',
    sourceType: 'Contract award',
    sourceLink: 'https://www.find-tender.example.gov.uk/notice/broadmead-partner-2026',
    rawSummary:
      'Bristol City Council names Trelawny Property Group as development partner for two office-led Broadmead blocks. Design services for the refurbishment phases not yet procured.',
    dateFound: '2026-06-27',
    aiStatus: 'Auto-classified',
    aiNote: 'Award identifies the buyer before design procurement — early capability conversation lands well.',
    reviewStatus: 'Unreviewed',
    confidence: 4,
  },
  {
    id: 'SIG-1043',
    title: 'Pasted URL: agent particulars — vacant 1980s office, Temple Quay',
    city: 'Bristol',
    district: 'Temple Quay',
    sectorGuess: 'Office',
    subSectorGuess: 'Office-to-living potential',
    sourceType: 'Pasted URL',
    sourceLink: 'https://example-agency.co.uk/instructions/temple-quay-house',
    rawSummary:
      'Pasted by AO: particulars for a fully vacant 8,700 m² 1980s office, quoting rents cut twice in twelve months. Deep plan; marginal for office retrofit at achievable rents.',
    dateFound: '2026-07-06',
    aiStatus: 'Pending',
    aiNote: 'Awaiting classification — vacancy verified, owner intent unknown.',
    reviewStatus: 'Unreviewed',
    confidence: 2,
  },
  {
    id: 'SIG-1037',
    title: 'Developer signal: land assembly near UWE Frenchay campus',
    city: 'Bristol',
    district: 'Frenchay',
    sectorGuess: 'Living',
    subSectorGuess: 'PBSA',
    sourceType: 'Company/developer signal',
    sourceLink: 'https://example-landdata.co.uk/assembly/frenchay-2026',
    rawSummary:
      'Halcyon Land & Development assembles three plots within walking distance of UWE Frenchay. Topographical survey observed on site; no application yet.',
    dateFound: '2026-07-02',
    aiStatus: 'Auto-classified',
    aiNote: 'Survey activity before planning — feasibility architect being (or about to be) appointed.',
    reviewStatus: 'Unreviewed',
    confidence: 3,
  },
  {
    id: 'SIG-1015',
    title: 'Event signal: Temple Quarter delivery update at UKREiiF',
    city: 'Bristol',
    district: 'Temple Quarter',
    sectorGuess: 'Living',
    subSectorGuess: 'Residential-led',
    sourceType: 'Event signal',
    sourceLink: 'https://example-ukreiif.co.uk/sessions/bristol-temple-quarter',
    rawSummary:
      'Delivery-body session confirmed next residential-led plots will come forward for soft market testing in 2027, with an emphasis on "design-led early feasibility".',
    dateFound: '2026-06-12',
    aiStatus: 'Auto-classified',
    aiNote: 'Programme signal only — long cycle; calendar checkpoint rather than active lead.',
    reviewStatus: 'Unreviewed',
    confidence: 2,
  },
]

export const SEED_OPPORTUNITIES: Opportunity[] = [
  // ── Office (6) ─────────────────────────────────────────────────────
  {
    id: 'OPP-2001',
    name: 'One Carter Lane repositioning',
    city: 'London',
    district: 'City of London',
    address: '1 Carter Lane, London EC4V',
    sector: 'Office',
    subSector: 'Office repositioning',
    client: 'Halewood Estates LLP',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.cityoflondon.gov.uk/26-00712-PREAPP',
    reference: '26/00712/PREAPP',
    stage: 'Pre-application',
    signalSummary:
      'Pre-application advice request for refurbishment, extension and re-cladding of a 13,800 m² 1992 office; single tenant vacates mid-2027 and the building sits at EPC D.',
    architecturalIssue:
      'Deep floorplates around a mid-plate core, low slab-to-slab heights and a dated arrival sequence. The retrofit-versus-extend decision drives everything: net-area recovery, MEES compliance and leasing strategy.',
    opportunityAngle:
      'The pre-app was filed by a planning consultant with no architect named — the owner is committing to repositioning before appointing a design team. A massing and net-area study now lands ahead of any competition.',
    relevance:
      'Directly matches our City retrofit track record (three comparable repositionings since 2022) and our floorplate-efficiency tooling.',
    commercialReason:
      'Full-service repositioning commission; fee scale comparable to our two largest current jobs, with a 2027 vacancy date forcing a decision this year.',
    nextAction: 'Partner letter to the Halewood asset director with a one-page position piece; offer a no-fee floorplate efficiency review.',
    status: 'Approach',
    scores: { sectorFit: 5, geographyFit: 5, stageTiming: 5, architecturalProblem: 5, feePotential: 4, relationshipRoute: 4, urgency: 5 },
    confidence: 4,
    owner: 'RK',
    notes: 'Halewood interviewed us in 2023 (lost to incumbent); asset director known to RK. Move fast — pre-app validated 6 Jul.',
    dateAdded: '2026-07-06',
    lastReviewed: '2026-07-07',
  },
  {
    id: 'OPP-2002',
    name: 'Albert Bridge House repositioning',
    city: 'Manchester',
    district: 'City Centre',
    address: 'Albert Bridge House, Bridge Street, Manchester M3',
    sector: 'Office',
    subSector: 'Office repositioning',
    client: 'Bridgewater Real Estate',
    sourceType: 'Market article',
    sourceLink: 'https://example-placenorthwest.co.uk/albert-bridge-house-sale',
    reference: 'MKT-ABH-M3',
    stage: 'Acquisition complete — strategy forming',
    signalSummary:
      'Bridgewater completed on the 1960s Albert Bridge House campus stating "comprehensive repositioning" intent, with no design team named in coverage or on the record.',
    architecturalIssue:
      'A listed-adjacent 1960s slab with strong embodied-carbon retention logic but failing façade, servicing and ground plane. Retain-and-extend versus partial redevelopment is the core study.',
    opportunityAngle:
      'New owner, stated intent, no team — the approach window is open until a design competition is scoped, typically one to two quarters after completion.',
    relevance: 'Our retrofit-first methodology and consented Manchester work give a credible northern platform; retention case suits our sustainability positioning.',
    commercialReason: 'Flagship-scale repositioning; a won study converts to multi-stage commission and anchors the Manchester pipeline.',
    nextAction: 'Request introduction via the acquiring fund’s planning advisor (shared contact); prepare a retain-versus-rebuild teaser board.',
    status: 'Research',
    scores: { sectorFit: 5, geographyFit: 4, stageTiming: 4, architecturalProblem: 5, feePotential: 4, relationshipRoute: 3, urgency: 3 },
    confidence: 3,
    owner: 'JM',
    notes: 'Converted from signal SIG-1020. Confirm whether Bridgewater runs design competitions or direct appointments.',
    dateAdded: '2026-06-19',
    lastReviewed: '2026-07-01',
    fromSignalId: 'SIG-1020',
  },
  {
    id: 'OPP-2003',
    name: 'Jewellery Quarter retrofit cluster',
    city: 'Birmingham',
    district: 'Jewellery Quarter',
    address: 'Three holdings, Vyse Street / Warstone Lane, Birmingham B18',
    sector: 'Office',
    subSector: 'Office retrofit',
    client: 'Multiple owners — cluster approach',
    sourceType: 'Market article',
    sourceLink: 'https://example-propertyweek.co.uk/birmingham-epc-cliff-2026',
    reference: 'RES-JQ-B18',
    stage: 'Concept — no live process',
    signalSummary:
      'Trade-press analysis names three sub-EPC-C Jewellery Quarter office holdings with leases rolling 2027–28 and no published retrofit plans.',
    architecturalIssue:
      'Small-floorplate heritage-fringe stock where standard retrofit playbooks fail — the design question is a repeatable light-touch upgrade kit that works across the cluster.',
    opportunityAngle:
      'Three owners facing the same 2030 EPC deadline invites a cluster study: one methodology, three prospective clients, positioning the practice as the JQ retrofit specialist.',
    relevance: 'Extends our retrofit toolkit into heritage-fringe stock; Birmingham presence is a stated growth aim.',
    commercialReason: 'Individually small fees, but the cluster route creates three at once and a citable specialism.',
    nextAction: 'AO to verify ownership and lease events for the three named holdings; draft a one-board cluster-study offer.',
    status: 'Watch',
    scores: { sectorFit: 4, geographyFit: 4, stageTiming: 3, architecturalProblem: 4, feePotential: 3, relationshipRoute: 2, urgency: 3 },
    confidence: 2,
    owner: 'AO',
    notes: 'Article is the only source so far — verify before any approach.',
    dateAdded: '2026-06-10',
    lastReviewed: '2026-06-15',
  },
  {
    id: 'OPP-2004',
    name: 'MCC civic estate strategy bid',
    city: 'Manchester',
    district: 'City Centre',
    address: 'Six civic office buildings, various M2/M60 sites',
    sector: 'Office',
    subSector: 'Office retrofit',
    client: 'Manchester City Council',
    sourceType: 'RFP',
    sourceLink: 'https://procontract.example.gov.uk/manchester/MCC-2026-EST-021',
    reference: 'MCC-2026-EST-021',
    stage: 'Tender open — deadline 31 Jul 2026',
    signalSummary:
      'Open tender for a multidisciplinary estate strategy: rationalisation, retrofit options and a net-zero pathway across six civic office buildings; quality-weighted 60/40.',
    architecturalIssue:
      'Portfolio triage across mixed-era civic stock: which buildings to keep, retrofit or release — a workplace-strategy and retrofit question at estate scale, not six separate refurbs.',
    opportunityAngle:
      'Public estate strategies convert into framework positions and delivery commissions, and the client relationship typically survives political cycles.',
    relevance: 'Our 2024 civic retrofit study is a direct, current reference; workplace + retrofit combination matches the stated evaluation weighting.',
    commercialReason: 'Study fee estimated £120–180k with the strongest known route into multi-year public-sector delivery work in the city.',
    nextAction: 'Bid/no-bid at Monday partners’ meeting; if bid, SB fixes the sustainability sub-consultant by 17 Jul.',
    status: 'Bid/RFP',
    scores: { sectorFit: 4, geographyFit: 4, stageTiming: 5, architecturalProblem: 4, feePotential: 5, relationshipRoute: 4, urgency: 5 },
    confidence: 5,
    owner: 'SB',
    notes: 'Two-stage quality/price. Known to the client team from the 2024 study. 16-day runway is adequate only if the team is fixed early.',
    dateAdded: '2026-07-06',
    lastReviewed: '2026-07-07',
  },
  {
    id: 'OPP-2005',
    name: 'Temple Quay stranded-asset study',
    city: 'Bristol',
    district: 'Temple Quay',
    address: 'Temple Quay House, Bristol BS1',
    sector: 'Office',
    subSector: 'Stranded office asset',
    client: 'Undetermined — fund-held',
    sourceType: 'Pasted URL',
    sourceLink: 'https://example-agency.co.uk/instructions/temple-quay-house',
    reference: 'RES-TQ-BS1',
    stage: 'Concept — no live process',
    signalSummary:
      'Fully vacant 8,700 m² 1980s office with rents cut twice in twelve months; deep plan makes office retrofit marginal at achievable Bristol rents.',
    architecturalIssue:
      'Highest-and-best-use question: deep-plan office versus residential or student conversion, gated by daylight, noise and core positions.',
    opportunityAngle: 'A short use-comparison study is exactly what the fund needs before its next valuation cycle — small fee, decision-shaping position.',
    relevance: 'Bridges both practice sectors; demonstrates the feasibility offer in a target growth city.',
    commercialReason: 'Entry-level fee now, but conversion (if it stacks) is a major commission and Bristol reference.',
    nextAction: 'Parked — no decision-maker identified. Re-open if a disposal or planning move appears.',
    status: 'Dormant',
    scores: { sectorFit: 4, geographyFit: 4, stageTiming: 3, architecturalProblem: 4, feePotential: 3, relationshipRoute: 1, urgency: 2 },
    confidence: 2,
    owner: 'AO',
    notes: 'Watch the title register — a sale would change the play to buyer-side feasibility.',
    dateAdded: '2026-06-08',
    lastReviewed: '2026-06-20',
  },
  {
    id: 'OPP-2006',
    name: 'Meridian Wharf HQ new build',
    city: 'London',
    district: 'Tower Hamlets',
    address: 'Meridian Wharf, Marsh Wall, London E14',
    sector: 'Office',
    subSector: 'New build office',
    client: 'Meridian Group',
    sourceType: 'Company/developer signal',
    sourceLink: 'https://example-costar.co.uk/meridian-wharf-hq-2026',
    reference: 'DEV-MW-E14',
    stage: 'Feasibility — occupier-led',
    signalSummary:
      'Meridian Group confirmed it is consolidating three London offices into a single built-to-suit HQ and has optioned a Marsh Wall site; delivery developer not yet selected.',
    architecturalIssue:
      'Occupier-led HQ brief on a constrained wharf site: workplace strategy, massing against riverside daylight constraints, and a public ground plane the borough will demand.',
    opportunityAngle:
      'Occupier is choosing its delivery partner — architect relationships formed now travel with the deal regardless of which developer wins.',
    relevance: 'Workplace/HQ is a named sub-sector strength; our E14 consented scheme is a direct precedent.',
    commercialReason: 'New-build HQ at this scale would be the practice’s largest office instruction of the cycle.',
    nextAction: 'Discuss internally: approach Meridian’s property director directly or via the two shortlisted developers (we know both).',
    status: 'Discuss internally',
    scores: { sectorFit: 5, geographyFit: 5, stageTiming: 3, architecturalProblem: 4, feePotential: 5, relationshipRoute: 3, urgency: 2 },
    confidence: 3,
    owner: 'RK',
    notes: 'Occupier timelines slip — do not over-resource before the developer shortlist is confirmed.',
    dateAdded: '2026-07-07',
    lastReviewed: '2026-07-07',
  },
  // ── Living (6) ─────────────────────────────────────────────────────
  {
    id: 'OPP-2007',
    name: 'Stratford co-living redesign',
    city: 'London',
    district: 'Newham',
    address: '148–164 Stratford High Street, London E15',
    sector: 'Living',
    subSector: 'Co-living',
    client: 'Skyfield Living',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.newham.gov.uk/26-00544-FUL',
    reference: '26/00544/FUL',
    stage: 'Refused at committee — pre-appeal',
    signalSummary:
      '702-unit co-living tower refused at committee against officer recommendation: massing, wind and ground-floor deadening cited. Appeal deadline 19 Aug 2026.',
    architecturalIssue:
      'All three refusal reasons are design-solvable — the tower carries its bulk in the wrong place and the podium turns a blank core to the high street. A re-sectioned scheme could retain most units.',
    opportunityAngle:
      'Refused against officer advice is the highest-value redesign signal: the principle of use is winnable, the design is not. A compelling redesign sketch influences the appeal-versus-redesign decision.',
    relevance: 'Our consented east London co-living scheme answered near-identical wind and podium objections.',
    commercialReason: 'Full redesign-to-consent mandate at 700 units; sector-defining reference if consented.',
    nextAction: 'Partner review of the committee webcast and refusal notice; decide the approach route before Skyfield’s appeal deadline (19 Aug).',
    status: 'Discuss internally',
    scores: { sectorFit: 5, geographyFit: 5, stageTiming: 5, architecturalProblem: 5, feePotential: 4, relationshipRoute: 3, urgency: 5 },
    confidence: 4,
    owner: 'SB',
    notes: 'Converted from signal SIG-1027. Incumbent may be retained for appeal — our pitch is explicitly the redesign route.',
    dateAdded: '2026-07-07',
    lastReviewed: '2026-07-08',
    fromSignalId: 'SIG-1027',
  },
  {
    id: 'OPP-2008',
    name: 'Digbeth PBSA recovery',
    city: 'Birmingham',
    district: 'Digbeth',
    address: '88–102 Digbeth High Street, Birmingham B5',
    sector: 'Living',
    subSector: 'PBSA',
    client: 'Northgate Student Living',
    sourceType: 'Planning',
    sourceLink: 'https://planning.example.birmingham.gov.uk/2026-02981-PA',
    reference: '2026/02981/PA',
    stage: 'Refused — pre-appeal',
    signalSummary:
      '480-bed PBSA refused on heritage-edge massing and amenity; officers supported the student-use principle. Twelve-week appeal window running.',
    architecturalIssue:
      'Massing steps the wrong way against the conservation edge and amenity is squeezed by a single-aspect block; a courtyard re-plan likely recovers ~90% of beds.',
    opportunityAngle:
      'Northgate must choose appeal (18 months) or redesign (9 months); a redesign sketch pack tilts that choice and positions us for the mandate.',
    relevance: 'Two consented PBSA schemes against comparable heritage objections in the current portfolio.',
    commercialReason: 'Redesign-to-consent commission plus entry to Northgate’s five-city development pipeline.',
    nextAction: 'Prepare the counter-massing study from public drawings; SB to route the approach via Northgate’s planning advisor.',
    status: 'Research',
    scores: { sectorFit: 5, geographyFit: 4, stageTiming: 5, architecturalProblem: 5, feePotential: 4, relationshipRoute: 2, urgency: 4 },
    confidence: 4,
    owner: 'SB',
    notes: 'Same applicant group as our 2024 Leeds pursuit — check conflict history before approach.',
    dateAdded: '2026-06-30',
    lastReviewed: '2026-07-05',
  },
  {
    id: 'OPP-2009',
    name: 'Castlefield BTR feasibility',
    city: 'Manchester',
    district: 'Castlefield',
    address: 'Canal-side site, Castlefield, Manchester M15',
    sector: 'Living',
    subSector: 'BTR',
    client: 'Vela Living',
    sourceType: 'Company/developer signal',
    sourceLink: 'https://example-placenorthwest.co.uk/vela-castlefield-2026',
    reference: 'DEV-CF-M15',
    stage: 'Site acquired — consent review',
    signalSummary:
      'Vela Living acquired a canal-side site with a lapsed 2019 consent for 280 homes, stating it will review the consented scheme against current standards.',
    architecturalIssue:
      'The lapsed scheme pre-dates current fire, daylight and sustainability standards — a re-plan will change cores, unit mix and massing, effectively a new design within a known envelope.',
    opportunityAngle: 'A "review against current standards" is a feasibility commission by another name, and no architect is attached post-acquisition.',
    relevance: 'BTR re-plan work matches our living-sector methodology; canal-side heritage context suits the portfolio.',
    commercialReason: 'Feasibility now, full commission if the revised scheme proceeds; Vela is building a northern pipeline.',
    nextAction: 'JM to contact Vela’s development director (met at UKREiiF) proposing a consent-review workshop.',
    status: 'Research',
    scores: { sectorFit: 5, geographyFit: 4, stageTiming: 4, architecturalProblem: 3, feePotential: 4, relationshipRoute: 3, urgency: 3 },
    confidence: 3,
    owner: 'JM',
    notes: 'Move before the review is internalised — Vela used an in-house team on its last two schemes.',
    dateAdded: '2026-07-06',
    lastReviewed: '2026-07-07',
  },
  {
    id: 'OPP-2010',
    name: 'UWE Frenchay PBSA feasibility',
    city: 'Bristol',
    district: 'Frenchay',
    address: 'Assembled plots, Frenchay Park Road, Bristol BS16',
    sector: 'Living',
    subSector: 'PBSA',
    client: 'Halcyon Land & Development',
    sourceType: 'Company/developer signal',
    sourceLink: 'https://example-landdata.co.uk/assembly/frenchay-2026',
    reference: 'DEV-FR-BS16',
    stage: 'Concept / feasibility',
    signalSummary:
      'Halcyon has assembled three plots within walking distance of UWE Frenchay; topographical survey observed on site with no application yet filed.',
    architecturalIssue:
      'Suburban-campus-edge PBSA: massing against neighbouring houses, single-aspect avoidance on constrained plots, and a green-belt-adjacent landscape argument.',
    opportunityAngle: 'Surveys before planning mean a feasibility architect is being appointed now — the window closes when one signs.',
    relevance: 'PBSA feasibility is a core service; the practice has an existing relationship with Halcyon’s demand consultant.',
    commercialReason: 'Feasibility-to-planning commission in a growth city, with a repeat-client developer.',
    nextAction: 'AO to confirm appointment status via the demand consultant this week; prepare a one-board capacity teaser.',
    status: 'Watch',
    scores: { sectorFit: 5, geographyFit: 4, stageTiming: 4, architecturalProblem: 3, feePotential: 3, relationshipRoute: 3, urgency: 3 },
    confidence: 3,
    owner: 'AO',
    notes: 'If an architect is already appointed, move to Dormant and hold for the planning application.',
    dateAdded: '2026-07-02',
    lastReviewed: '2026-07-06',
  },
  {
    id: 'OPP-2011',
    name: 'Southwark university estates partnership',
    city: 'London',
    district: 'Southwark',
    address: 'Halls estate, various SE1 sites',
    sector: 'Living',
    subSector: 'Student accommodation',
    client: 'South London university (via former client)',
    sourceType: 'Manual intelligence',
    sourceLink: 'https://example.internal/crm/contact-4471',
    reference: 'INT-2026-044',
    stage: 'Live conversation',
    signalSummary:
      'Former client, now Director of Estates, described a condition-driven halls refurbishment backlog and a stalled residences masterplan in a direct conversation.',
    architecturalIssue:
      'Ageing 1960s–90s halls needing bedroom-standard uplift and MEES compliance, plus densification testing on a constrained urban campus.',
    opportunityAngle: 'A warm, named decision-maker with a stated problem and no procurement yet — the classic pre-RFP relationship route.',
    relevance: 'Halls refurbishment methodology is proven; the relationship is first-hand and current.',
    commercialReason: 'Direct study work near-term, and pole position if the masterplan is re-procured.',
    nextAction: 'JM to propose a campus walkabout and a no-fee condition-priorities workshop, w/c 13 Jul.',
    status: 'Live conversation',
    scores: { sectorFit: 5, geographyFit: 5, stageTiming: 4, architecturalProblem: 3, feePotential: 4, relationshipRoute: 5, urgency: 3 },
    confidence: 4,
    owner: 'JM',
    notes: 'Keep the first proposal light — relationship investment as much as fee.',
    dateAdded: '2026-06-26',
    lastReviewed: '2026-07-06',
  },
  {
    id: 'OPP-2012',
    name: 'Bloomsbury hotel-to-living conversion',
    city: 'London',
    district: 'Camden',
    address: '22–30 Tavistock Place, London WC1',
    sector: 'Living',
    subSector: 'Hotel-to-living',
    client: 'Perrin & Vale Estates',
    sourceType: 'CSV import',
    sourceLink: 'https://example-agency.co.uk/particulars/bloomsbury-hotel-2026',
    reference: 'CSV-BLM-WC1',
    stage: 'Concept — owner testing options',
    signalSummary:
      '190-key 1970s hotel marketed with "potential for alternative uses including student and co-living, subject to planning" — surfaced via the weekly agency CSV import.',
    architecturalIssue:
      'Hotel-to-living conversion: corridor-to-cluster re-planning, daylight to deep rooms, amenity ratios, and a ground floor built for coach drop-off that living uses do not need.',
    opportunityAngle: 'Marketing for "alternative uses" invites buyer-side feasibility — a conversion study underwrites any serious bid.',
    relevance: 'Hotel-to-living testing extends our conversion toolkit; Bloomsbury student demand is well evidenced.',
    commercialReason: 'Buyer-side study fees now; the appointed feasibility architect usually carries into delivery.',
    nextAction: 'Identify the two most likely acquirers and offer a pre-bid feasibility view; hold effort until a sale process timetable is known.',
    status: 'Watch',
    scores: { sectorFit: 4, geographyFit: 5, stageTiming: 3, architecturalProblem: 4, feePotential: 3, relationshipRoute: 2, urgency: 2 },
    confidence: 2,
    owner: 'AO',
    notes: 'Stale risk — marketing particulars age fast; re-verify in two weeks.',
    dateAdded: '2026-06-05',
    lastReviewed: '2026-06-12',
  },
]

export const SEED_ACTIVITY: ActivityEntry[] = [
  { date: '2026-07-08', text: 'Stratford co-living redesign reviewed — appeal deadline confirmed 19 Aug; urgency raised to 5.', href: '/pipeline/OPP-2007' },
  { date: '2026-07-07', text: 'Signal converted: Stratford High Street refusal → Stratford co-living redesign.', href: '/pipeline/OPP-2007' },
  { date: '2026-07-07', text: 'Added: Meridian Wharf HQ new build (developer signal, RK).', href: '/pipeline/OPP-2006' },
  { date: '2026-07-07', text: 'CSV import: 11 rows processed, 1 matched — Bloomsbury hotel signal created.', href: '/signals' },
  { date: '2026-07-06', text: 'Added: One Carter Lane repositioning and MCC civic estate strategy bid.', href: '/pipeline/OPP-2001' },
  { date: '2026-07-06', text: 'AI triage: 3 new signals classified (Gresham Street, Vela Castlefield, Temple Quay URL).', href: '/signals' },
  { date: '2026-07-05', text: 'Digbeth PBSA recovery — counter-massing study scoped; approach route via planning advisor.', href: '/pipeline/OPP-2008' },
  { date: '2026-07-04', text: 'RFP detected: MCC civic office estate strategy, deadline 31 Jul (quality-weighted 60/40).', href: '/signals' },
]
