import type { ActivityEntry, Opportunity, RfpWatchItem } from './types'

/**
 * Sample content — fictional but realistic London examples.
 * Six office retrofit / repositioning leads, six PBSA / living leads,
 * across planning, RFP, award, stalled-scheme, market and manual signals.
 */
export const OPPORTUNITIES: Opportunity[] = [
  // ── Office retrofit / repositioning ────────────────────────────────
  {
    id: 'OR-2026-014',
    name: 'Aldgate House, Jewry Street',
    sector: 'office-retrofit',
    borough: 'City of London',
    address: '12–20 Jewry Street, London EC3N 2EX',
    client: 'Meridian Estates LLP',
    sourceType: 'Planning',
    sourceLabel: 'City of London planning register',
    sourceLink: 'https://www.planning2.cityoflondon.gov.uk/example/26-00412-PREAPP',
    reference: '26/00412/PREAPP',
    stage: 'Pre-application',
    signalKind: 'Asset repositioning',
    signalSummary:
      'Pre-application advice request logged for "refurbishment, extension and reconfiguration" of a 1994 office building (11,600 m² GIA). Single tenant vacates mid-2027; EPC currently D.',
    architecturalIssue:
      'Deep 1990s floorplates with a mid-plate core, low floor-to-ceiling heights and a dated granite-clad arrival sequence. MEES 2030 compliance forces intervention; the question is reclad-and-extend versus deep retrofit.',
    opportunityAngle:
      'Owner is committing to a repositioning route before appointing a design team — the pre-app was filed by a planning consultant, not an architect. A design-led massing and net-area study now would land ahead of any procurement.',
    relevance:
      'Directly matches our City retrofit track record (three comparable repositionings since 2022) and our floorplate/core efficiency tooling. Fee scale consistent with full-service appointment.',
    nextAction: 'Partner-level letter to Meridian asset director with a one-page retrofit position piece; offer a no-fee floorplate efficiency review.',
    status: 'Approach',
    scores: {
      sectorFit: 5,
      stageTiming: 5,
      architecturalProblem: 5,
      feePotential: 4,
      relationshipRoute: 4,
      urgency: 4,
    },
    confidence: 80,
    notes:
      'Meridian previously interviewed us (unsuccessfully) for Fenchurch Street scheme in 2023 — feedback was positive on design, procurement went to incumbent. Asset director known to RK.',
    owner: 'RK',
    dateAdded: '2026-06-11',
    lastReviewed: '2026-07-06',
    ai: {
      executiveSummary:
        'A credible, near-term repositioning of a 1990s City office with a hard 2027 vacancy date and no architect yet attached. The pre-application filing is the strongest early signal type: intent is confirmed, design route is not.',
      classification: 'Pre-RFP planning signal — asset repositioning, City core.',
      likelyIssue:
        'Retrofit-versus-extend decision on a deep-plan 1990s frame; MEES-driven services replacement; arrival and ground-plane quality below current City leasing standards.',
      commercialRelevance:
        'Full-service retrofit commission of a scale the practice has delivered three times since 2022; strong reference-ability if won.',
      recommendedAction:
        'Direct approach within two weeks, before a design competition is scoped. Lead with the floorplate efficiency review.',
      confidenceNote:
        'High — signal is a verified planning register entry naming the owner; vacancy date corroborated by leasing press.',
      falsePositiveRisk:
        'Low–medium. Pre-apps are sometimes filed to test value for disposal rather than to build; a sale would remove the commission but keep the buyer relationship relevant.',
    },
  },
  {
    id: 'OR-2026-009',
    name: 'Farringdon Works, Cowcross Street',
    sector: 'office-retrofit',
    borough: 'Islington',
    address: '45 Cowcross Street, London EC1M 6DR',
    client: 'Cowcross Property Ltd',
    sourceType: 'Planning',
    sourceLabel: 'Islington planning register',
    sourceLink: 'https://planning.islington.gov.uk/example/P2025-1877-FUL',
    reference: 'P2025/1877/FUL',
    stage: 'Stalled — 3rd amendment round',
    signalKind: 'Stalled scheme',
    signalSummary:
      'Full application for refurbishment plus two-storey extension has been in amendment cycles for 14 months. Third revision reduces the extension again after daylight objections from residents to the north.',
    architecturalIssue:
      'The extension massing keeps failing daylight tests because the parti is wrong, not because it is too big — the added volume sits on the wrong side of the roof. A redesigned stepped section could likely recover most of the area.',
    opportunityAngle:
      'Fourteen months of amendments suggests the current design team relationship is under strain and viability is eroding. Owners in this position are receptive to a fresh design view framed as "unlocking consent".',
    relevance:
      'We have consented two comparable Clerkenwell rooftop extensions against daylight objections; strong precedent pack available.',
    nextAction: 'Build a one-page massing counter-study from public drawings; JM to identify route to the owner (agent is Colliers-equivalent).',
    status: 'Research',
    scores: {
      sectorFit: 5,
      stageTiming: 4,
      architecturalProblem: 5,
      feePotential: 4,
      relationshipRoute: 2,
      urgency: 3,
    },
    confidence: 65,
    notes: 'Approaching a live application’s owner needs care — position as consent-recovery expertise, never as criticism of the incumbent on record.',
    owner: 'JM',
    dateAdded: '2026-05-28',
    lastReviewed: '2026-06-12',
    ai: {
      executiveSummary:
        'A stalled Clerkenwell refurbishment-and-extension application showing the classic three-amendment pattern that precedes either withdrawal or a design team change.',
      classification: 'Pre-RFP planning signal — stalled scheme, consent risk.',
      likelyIssue:
        'Daylight/sunlight failure driven by extension massing strategy; probable viability pressure as amendment costs accumulate.',
      commercialRelevance:
        'Consent-recovery redesign, potentially expanding to full delivery if the incumbent exits.',
      recommendedAction:
        'Prepare the counter-massing study before approach; do not contact until the route to the owner (not the agent) is confirmed.',
      confidenceNote:
        'Medium — the stall is documented on the register, but the owner’s appetite for a team change is inferred, not evidenced.',
      falsePositiveRisk:
        'Medium. The third amendment may yet be consented, which closes the redesign angle (though a delivery-architect angle could remain).',
    },
  },
  {
    id: 'OR-2026-017',
    name: 'Vauxhall Cross Business Centre',
    sector: 'office-retrofit',
    borough: 'Lambeth',
    address: '85 South Lambeth Road, London SW8 1RL',
    client: 'Undetermined — asset held by Arcus Capital (fund)',
    sourceType: 'Market signal',
    sourceLabel: 'Vacancy data / agent particulars',
    sourceLink: 'https://example-agency.co.uk/instructions/vauxhall-cross-business-centre',
    reference: 'MKT-VX-085',
    stage: 'Concept — no live application',
    signalKind: 'Office-to-living potential',
    signalSummary:
      '9,300 m² 1980s office fully vacant for 11 months; quoted rents cut twice. Fund-held, over-rented on paper against the Vauxhall office market.',
    architecturalIssue:
      'Slab-to-slab heights and plan depth are marginal for office retrofit at achievable rents; the building may work harder as residential or student conversion, subject to noise (railway) and daylight testing.',
    opportunityAngle:
      'A short highest-and-best-use study (office retrofit vs conversion) is precisely the piece of thinking the fund needs before its next valuation cycle — small fee, decision-shaping position.',
    relevance:
      'Sits across both pilot sectors: our office repositioning experience plus living-sector conversion testing. Good demonstration case for the practice’s feasibility offer.',
    nextAction: 'Desktop massing and use-comparison this month; hold for approach until Arcus contact is identified.',
    status: 'Watch',
    scores: {
      sectorFit: 4,
      stageTiming: 3,
      architecturalProblem: 4,
      feePotential: 3,
      relationshipRoute: 2,
      urgency: 2,
    },
    confidence: 45,
    notes: 'No decision-maker identified yet. Watch for a disposal listing — that would change the play to buyer-side feasibility.',
    owner: 'AO',
    dateAdded: '2026-06-19',
    lastReviewed: '2026-06-19',
    ai: {
      executiveSummary:
        'A long-vacant 1980s Vauxhall office whose economics likely no longer support office use — an early office-to-living conversion candidate with no live process attached.',
      classification: 'Market signal — vacancy distress, conversion potential.',
      likelyIssue:
        'Marginal office retrofit economics; conversion feasibility gated by railway noise, daylight and core positions.',
      commercialRelevance:
        'Feasibility-stage commission now; potential full conversion commission later.',
      recommendedAction: 'Low-cost desktop study; no approach until a named asset manager is identified.',
      confidenceNote:
        'Low–medium — the vacancy is verified, but owner intent is entirely unknown.',
      falsePositiveRisk:
        'High. The fund may simply re-let at lower rents or dispose; both remove the near-term commission.',
    },
  },
  {
    id: 'OR-2026-021',
    name: 'LB Camden corporate estate strategy',
    sector: 'office-retrofit',
    borough: 'Camden',
    address: 'Five civic office buildings, various NW1/WC1 sites',
    client: 'London Borough of Camden',
    sourceType: 'RFP',
    sourceLabel: 'Council procurement portal',
    sourceLink: 'https://procontract.example.gov.uk/camden/CAM-2026-EST-014',
    reference: 'CAM-2026-EST-014',
    stage: 'Tender open — deadline 24 Jul 2026',
    signalSummary:
      'Open tender for multidisciplinary feasibility: rationalisation and retrofit options across five civic office buildings, including workplace strategy, net-zero pathway and disposal testing.',
    architecturalIssue:
      'Mixed-era civic stock (1930s–1990s) with poor space utilisation; the brief asks which buildings to keep, retrofit or release — a portfolio-level design question, not five separate refurbs.',
    opportunityAngle:
      'Public-sector estate strategies convert into framework positions and delivery commissions; the incumbent relationship formed here typically survives two political cycles.',
    relevance:
      'We hold a live public-sector reference (2024 civic retrofit study) and the workplace + retrofit combination matches the tender’s stated evaluation weighting (60% quality).',
    nextAction: 'Bid/no-bid review at Monday partners’ meeting; if bid, SB assembles sustainability sub-consultant by 14 Jul.',
    status: 'Discuss internally',
    scores: {
      sectorFit: 4,
      stageTiming: 5,
      architecturalProblem: 4,
      feePotential: 4,
      relationshipRoute: 4,
      urgency: 5,
    },
    confidence: 90,
    notes: 'Estimated fee band £120–180k for the study phase. Two-stage quality/price 60/40. We are known to the client team from the 2024 study.',
    owner: 'SB',
    dateAdded: '2026-07-06',
    lastReviewed: '2026-07-07',
    rfp: {
      classification: 'Bid now',
      buyer: 'London Borough of Camden',
      deadline: '2026-07-24',
      portal: 'ProContract (example)',
    },
    ai: {
      executiveSummary:
        'A live, well-matched public tender: portfolio retrofit strategy for Camden’s civic offices with quality-weighted evaluation and a warm client relationship.',
      classification: 'RFP — bid now; public estate strategy.',
      likelyIssue:
        'Portfolio triage across mixed-era stock: retrofit-versus-release logic, utilisation evidence, and a credible net-zero pathway.',
      commercialRelevance:
        'Direct fee now plus the strongest known route to multi-year public-sector delivery work.',
      recommendedAction: 'Bid decision this week; the 16-day runway is adequate only if the team is fixed by 14 July.',
      confidenceNote: 'High — the tender is published and verified; only win probability is uncertain.',
      falsePositiveRisk: 'Low. The process is real; the risk is competitive, not informational.',
    },
  },
  {
    id: 'OR-2026-019',
    name: 'Grafton Quarter repositioning',
    sector: 'office-retrofit',
    borough: 'Croydon',
    address: 'Grafton Quarter, Dingwall Road, Croydon CR0',
    client: 'Trelawny Property Group (development partner)',
    sourceType: 'Award',
    sourceLabel: 'Contract award notice',
    sourceLink: 'https://www.find-tender.example.gov.uk/notice/grafton-quarter-2026',
    reference: 'FTS-2026-088122',
    stage: 'Partner appointed — design team forming',
    signalSummary:
      'Croydon Council has appointed Trelawny as development partner for the office-led Grafton Quarter blocks. Award notice covers development management; design services for the refurbishment phases are not yet procured.',
    architecturalIssue:
      'Two 1970s–80s slab blocks with asbestos-era servicing and weak ground-floor frontage onto a rising public-realm corridor; phased retrofit around partial occupancy is the core design problem.',
    opportunityAngle:
      'Award signals tell you who is about to buy design services. Trelawny’s panel for this scale is short and they are new to Croydon — an early capability conversation lands well now.',
    relevance: 'Matches our occupied-retrofit and town-centre repositioning experience; Croydon references would open the wider south-London pipeline.',
    nextAction: 'RK to request an introduction via the cost consultant on the award (shared contact from 2023 project).',
    status: 'Watch',
    scores: {
      sectorFit: 4,
      stageTiming: 3,
      architecturalProblem: 4,
      feePotential: 4,
      relationshipRoute: 2,
      urgency: 3,
    },
    confidence: 55,
    notes: 'Timing risk: too early to know their procurement route (direct appointment vs mini-competition). Keep warm, low effort.',
    owner: 'RK',
    dateAdded: '2026-06-24',
    lastReviewed: '2026-07-01',
    ai: {
      executiveSummary:
        'A contract-award signal marking the moment before design procurement: Trelawny confirmed as partner for Croydon office blocks, architect not yet appointed.',
      classification: 'Award signal — buyer identified, design services pending.',
      likelyIssue: 'Phased occupied retrofit of 1970s–80s slab blocks with ground-plane and servicing renewal.',
      commercialRelevance: 'Multi-phase refurbishment commission; strategic entry into a regeneration-active borough.',
      recommendedAction: 'Warm introduction via shared consultant; hold formal approach until their procurement route is visible.',
      confidenceNote: 'Medium — the award is verified; the design-services route and timing are not yet public.',
      falsePositiveRisk: 'Medium. Trelawny may carry an in-house or framework architect into the scheme.',
    },
  },
  {
    id: 'OR-2026-022',
    name: 'Fleet House arrival & public realm',
    sector: 'office-retrofit',
    borough: 'City of London',
    address: 'Fleet House, New Bridge Street, London EC4V',
    client: 'Lanark Asset Management',
    sourceType: 'Internal relationship',
    sourceLabel: 'Direct conversation — former client',
    sourceLink: 'https://example.internal/crm/lanark-asset-management',
    reference: 'INT-2026-031',
    stage: 'Feasibility conversation',
    signalKind: 'Asset repositioning',
    signalSummary:
      'Former client, now at Lanark, raised occupier-survey feedback flagging the building’s arrival sequence and forecourt as the main leasing objection. Asked informally "what a light-touch fix looks like".',
    architecturalIssue:
      'Compressed 1980s lobby behind a service-dominated forecourt; wayfinding and accessibility below current occupier expectations. A reception, frontage and public-realm upgrade rather than a full retrofit.',
    opportunityAngle:
      'Small entry commission with a named, warm decision-maker — the classic wedge into a larger asset plan (rooftop plant renewal is due 2028).',
    relevance: 'Fast, visible win; our Fleet Street-area frontage work is directly citable. Low cost of sale.',
    nextAction: 'JM to send three-option arrival-sequence sketch pack and propose a walkabout w/c 13 Jul.',
    status: 'Approach',
    scores: {
      sectorFit: 4,
      stageTiming: 4,
      architecturalProblem: 3,
      feePotential: 2,
      relationshipRoute: 5,
      urgency: 3,
    },
    confidence: 70,
    notes: 'Keep proposal light — this is a relationship investment as much as a fee. Flag 2028 plant renewal in the pack.',
    owner: 'JM',
    dateAdded: '2026-07-07',
    lastReviewed: '2026-07-07',
    ai: {
      executiveSummary:
        'A warm, small-scale arrival and public-realm upgrade raised directly by a former client — low fee, high relationship value, fast decision.',
      classification: 'Internal relationship — entry commission.',
      likelyIssue: 'Lobby, frontage and forecourt legibility; accessibility compliance in the arrival sequence.',
      commercialRelevance: 'Modest immediate fee; positions the practice for the 2028 plant-renewal and wider repositioning cycle.',
      recommendedAction: 'Respond within the week while the occupier-survey finding is live internally at Lanark.',
      confidenceNote: 'High on intent (first-hand conversation); medium on budget being approved this year.',
      falsePositiveRisk: 'Low–medium. Informal asks sometimes evaporate at budget stage; the sketch pack limits our exposure.',
    },
  },

  // ── PBSA / living ──────────────────────────────────────────────────
  {
    id: 'PL-2026-011',
    name: 'Wick Lane Yard PBSA feasibility',
    sector: 'pbsa-living',
    borough: 'Tower Hamlets',
    address: 'Wick Lane, Hackney Wick, London E3',
    client: 'Halcyon Land & Development',
    sourceType: 'Market signal',
    sourceLabel: 'Land assembly intelligence',
    sourceLink: 'https://example-landdata.co.uk/assembly/wick-lane-e3',
    reference: 'MKT-WL-E3',
    stage: 'Concept / feasibility',
    signalKind: 'PBSA / living feasibility',
    signalSummary:
      'Halcyon has assembled three adjoining yard plots within walking distance of the UCL East and Loughborough London campuses. No application yet; site hoarding renewed and topo survey observed on site.',
    architecturalIssue:
      'Tight urban yard site in a transitioning industrial context: massing against the A12 edge, amenity and daylight in deep plots, and a ground floor that must answer Hackney Wick’s workspace-protection policies.',
    opportunityAngle:
      'Surveys before planning means a feasibility architect is being — or is about to be — appointed. The student-demand story (UCL East growth) writes itself; the planning story does not, and that is the harder problem we can lead with.',
    relevance: 'Two consented PBSA schemes in east London in the last cycle; existing relationship with the demand consultant Halcyon uses.',
    nextAction: 'AO to confirm appointment status via demand consultant; prepare capacity study teaser (one board).',
    status: 'Research',
    scores: {
      sectorFit: 5,
      stageTiming: 4,
      architecturalProblem: 4,
      feePotential: 4,
      relationshipRoute: 3,
      urgency: 3,
    },
    confidence: 60,
    notes: 'If an architect is already appointed, reclassify to Dormant and hold for the planning application.',
    owner: 'AO',
    dateAdded: '2026-06-30',
    lastReviewed: '2026-07-03',
    ai: {
      executiveSummary:
        'A pre-application PBSA site assembly beside the UCL East cluster, with physical survey activity indicating imminent design procurement.',
      classification: 'Market signal — PBSA feasibility, pre-planning.',
      likelyIssue: 'Massing and amenity on constrained yard plots; industrial-land and workspace policy negotiation.',
      commercialRelevance: 'Feasibility-to-planning commission in a core practice sector, near a strengthening demand cluster.',
      recommendedAction: 'Verify appointment status within two weeks — the window closes when a feasibility architect signs.',
      confidenceNote: 'Medium — assembly and survey activity are observed; PBSA (rather than co-living or workspace) use is inferred.',
      falsePositiveRisk: 'Medium. The assembly could target light-industrial or build-to-rent uses instead.',
    },
  },
  {
    id: 'PL-2026-006',
    name: 'Holloway Road PBSA — refused',
    sector: 'pbsa-living',
    borough: 'Islington',
    address: '367–375 Holloway Road, London N7',
    client: 'Northgate Student Living',
    sourceType: 'Planning',
    sourceLabel: 'Islington planning register — committee decision',
    sourceLink: 'https://planning.islington.gov.uk/example/P2025-2214-FUL',
    reference: 'P2025/2214/FUL',
    stage: 'Refused at committee — pre-appeal',
    signalKind: 'Refusal',
    signalSummary:
      '462-bed PBSA scheme refused at committee against officer recommendation. Reasons: excessive massing to the conservation-area edge, daylight impacts, and ground-floor deadening of the high street.',
    architecturalIssue:
      'All three refusal reasons are design-solvable: the scheme carries its height in the wrong place, and the podium turns a blank core to the high street. A re-sectioned massing with an active podium could retain ~90% of beds.',
    opportunityAngle:
      'Refused-at-committee against officer advice is the highest-value redesign signal: the principle of use is winnable, the design is not. Northgate must now choose appeal (18 months) or redesign (9 months) — a compelling redesign sketch influences that choice.',
    relevance: 'Our Caledonian Road consent (2024) answered near-identical conservation-edge objections; same case officer team.',
    nextAction: 'Partner review of committee webcast + refusal notice; decide approach route before Northgate’s appeal deadline (12 Aug).',
    status: 'Discuss internally',
    scores: {
      sectorFit: 5,
      stageTiming: 5,
      architecturalProblem: 5,
      feePotential: 4,
      relationshipRoute: 3,
      urgency: 5,
    },
    confidence: 75,
    notes: 'Incumbent architect may be retained for appeal. Our pitch is explicitly the redesign route, which is a different mandate.',
    owner: 'SB',
    dateAdded: '2026-06-03',
    lastReviewed: '2026-06-10',
    ai: {
      executiveSummary:
        'A large PBSA refusal where the use principle survived and the design did not — the strongest redesign opportunity currently on the radar, with a hard 12 August appeal deadline forcing the client’s decision.',
      classification: 'Pre-RFP planning signal — refusal, redesign route.',
      likelyIssue: 'Massing distribution against the conservation edge; podium activation; daylight to neighbouring terraces.',
      commercialRelevance: 'Full redesign-to-consent commission at 400+ beds; sector-defining reference if consented.',
      recommendedAction: 'Decide the approach inside three weeks; after the appeal is lodged the redesign window narrows sharply.',
      confidenceNote: 'High — refusal reasons and committee record are public and specific.',
      falsePositiveRisk: 'Low–medium. Northgate may appeal with the incumbent; even then a parallel redesign is sometimes commissioned as a hedge.',
    },
  },
  {
    id: 'PL-2026-013',
    name: 'Canning Town Riverside plots',
    sector: 'pbsa-living',
    borough: 'Newham',
    address: 'Riverside plots R2–R4, Canning Town, London E16',
    client: 'To be procured — landowner is a public regeneration body',
    sourceType: 'Regeneration prospectus',
    sourceLabel: 'Regeneration delivery prospectus 2026',
    sourceLink: 'https://example-regen.london/canning-town-prospectus-2026',
    reference: 'REG-CT-R2R4',
    stage: 'Prospectus published — soft market test expected Q4',
    signalKind: 'Regeneration site',
    signalSummary:
      'The 2026 delivery prospectus identifies plots R2–R4 for "living-led mixed use including student and co-living formats", with a soft market test signalled for Q4 2026.',
    architecturalIssue:
      'Riverside plots with flood-zone podium logic, wind exposure, and a masterplan grid drawn for an earlier commercial mix — early capacity testing will reshape what the market test asks for.',
    opportunityAngle:
      'Prospectus-stage sites reward architects who help write the question: capacity and typology testing for the landowner now positions us on either side of the eventual procurement.',
    relevance: 'Living-sector typology research is a stated practice priority; public-realm-led riverside work is in the portfolio.',
    nextAction: 'Request a briefing meeting with the regeneration body’s development team; monitor for the market-test notice.',
    status: 'Watch',
    scores: {
      sectorFit: 4,
      stageTiming: 3,
      architecturalProblem: 4,
      feePotential: 5,
      relationshipRoute: 2,
      urgency: 2,
    },
    confidence: 50,
    notes: 'Long-cycle lead. Calendar checkpoint set for October ahead of the expected market test.',
    owner: 'RK',
    dateAdded: '2026-06-16',
    lastReviewed: '2026-06-20',
    ai: {
      executiveSummary:
        'A publicly signalled living-led regeneration opportunity a full cycle ahead of procurement — low urgency, high eventual fee scale.',
      classification: 'Regeneration prospectus — pre-procurement positioning.',
      likelyIssue: 'Flood-podium ground condition, wind mitigation, and typology mix within an outdated masterplan grid.',
      commercialRelevance: 'Multi-plot living commission if positioned early; capacity-study work available sooner.',
      recommendedAction: 'One positioning meeting this quarter; otherwise hold effort until the Q4 market test.',
      confidenceNote: 'Medium — the prospectus is verified; programme dates in such documents routinely slip.',
      falsePositiveRisk: 'Medium. Regeneration programmes are re-scoped often; the plots may shift use or timescale.',
    },
  },
  {
    id: 'PL-2026-015',
    name: 'Filmworks North co-living amendment',
    sector: 'pbsa-living',
    borough: 'Ealing',
    address: 'Filmworks North plot, Ealing Broadway, London W5',
    client: 'Habitat & Co (operator) / plot owner TBC',
    sourceType: 'Planning',
    sourceLabel: 'Ealing planning register',
    sourceLink: 'https://pam.ealing.gov.uk/example/261334VAR',
    reference: '261334VAR',
    stage: 'S73 amendment submitted',
    signalKind: 'Planning amendment',
    signalSummary:
      'Section 73 application to convert the consented hotel element (140 keys) to co-living (188 units). A named operator — Habitat & Co — appears in the planning statement for the first time.',
    architecturalIssue:
      'Hotel-to-co-living conversion inside a consented envelope: corridor-to-cluster replanning, amenity ratio compliance, and a ground floor designed for hotel drop-off that co-living does not need.',
    opportunityAngle:
      'A new operator entering a consented scheme often triggers a delivery-architect procurement separate from the consent architect — and Habitat & Co is expanding its London pipeline.',
    relevance: 'Our co-living amenity benchmarking study (2025) is directly relevant; operator-side relationships are a growth aim.',
    nextAction: 'Track the amendment to decision; JM to seek an introduction to Habitat & Co’s development lead at the September living-sector forum.',
    status: 'Watch',
    scores: {
      sectorFit: 4,
      stageTiming: 4,
      architecturalProblem: 3,
      feePotential: 3,
      relationshipRoute: 2,
      urgency: 3,
    },
    confidence: 55,
    notes: 'The operator relationship matters more than this single plot — treat as a door-opener to their pipeline.',
    owner: 'JM',
    dateAdded: '2026-07-01',
    lastReviewed: '2026-07-04',
    ai: {
      executiveSummary:
        'A use-swap amendment that reveals a new co-living operator attaching to a consented Ealing scheme — a buyer signal as much as a project signal.',
      classification: 'Pre-RFP planning signal — amendment, operator entry.',
      likelyIssue: 'Cluster replanning within a fixed envelope; co-living amenity standards; ground-floor repurposing.',
      commercialRelevance: 'Delivery-architect role on this plot; relationship route into an expanding operator’s London pipeline.',
      recommendedAction: 'Low-effort tracking now; invest in the operator introduction rather than the plot.',
      confidenceNote: 'Medium — the amendment and operator naming are verified; the procurement split is inferred from sector practice.',
      falsePositiveRisk: 'Medium. The consent architect may carry the amendment through to delivery.',
    },
  },
  {
    id: 'PL-2026-020',
    name: 'London Universities housing framework',
    sector: 'pbsa-living',
    borough: 'Multiple (pan-London)',
    address: 'Estates across six university campuses',
    client: 'London university purchasing consortium',
    sourceType: 'RFP',
    sourceLabel: 'Find a Tender — framework notice',
    sourceLink: 'https://www.find-tender.example.gov.uk/notice/lu-housing-framework-2026',
    reference: 'FTS-2026-091455',
    stage: 'PQQ open — deadline 14 Aug 2026',
    signalSummary:
      'Four-year design-services framework for student accommodation: refurbishment of existing stock, feasibility for new-build, and condition-driven compliance work across six member universities.',
    architecturalIssue:
      'Framework scope centres on ageing 1960s–90s halls: bedroom-standard uplift, MEES compliance, and densification testing on existing campuses — repeat-methodology work rewarding a strong toolkit.',
    opportunityAngle:
      'Framework seats are the distribution channel for the whole PBSA refurb sector — a seat converts BD effort into a queue of call-offs rather than one-off pursuits.',
    relevance: 'Live PBSA portfolio plus refurbishment methodology; the consortium’s quality questions match our standard evidence pack at ~70%.',
    nextAction: 'SB to confirm PQQ go/no-go and lot selection (Lots 1 & 3) by 18 Jul; identify M&E partner for Lot 3.',
    status: 'Discuss internally',
    scores: {
      sectorFit: 5,
      stageTiming: 4,
      architecturalProblem: 3,
      feePotential: 4,
      relationshipRoute: 3,
      urgency: 4,
    },
    confidence: 85,
    notes: 'Framework terms cap fees but volume compensates. Reference projects must be < 5 years old — 2022 Mile End scheme qualifies until March.',
    owner: 'SB',
    dateAdded: '2026-07-07',
    lastReviewed: '2026-07-07',
    rfp: {
      classification: 'Framework route',
      buyer: 'London university purchasing consortium',
      deadline: '2026-08-14',
      portal: 'Find a Tender (example)',
    },
    ai: {
      executiveSummary:
        'A four-year university-housing framework whose lots align with the practice’s PBSA refurbishment strength — the highest-leverage single submission available this quarter.',
      classification: 'RFP — framework route.',
      likelyIssue: 'Repeatable refurbishment methodology for ageing halls; compliance-driven scope definition.',
      commercialRelevance: 'Converts sector BD into a call-off pipeline; stabilises living-sector workload across the cycle.',
      recommendedAction: 'Treat the PQQ as a priority submission; lot discipline matters more than breadth.',
      confidenceNote: 'High — notice verified; lot fee bands published.',
      falsePositiveRisk: 'Low. The framework is real; the risk is ranking below the seat cut-off.',
    },
  },
  {
    id: 'PL-2026-004',
    name: 'Blackfriars Road conversion pair',
    sector: 'pbsa-living',
    borough: 'Southwark',
    address: '190 & 196 Blackfriars Road, London SE1',
    client: 'Perrin & Vale Estates',
    sourceType: 'Manual research',
    sourceLabel: 'Press piece + desktop research',
    sourceLink: 'https://example-propertyweek.co.uk/blackfriars-alternative-use-2026',
    reference: 'RES-BF-190',
    stage: 'Concept — owner testing options',
    signalKind: 'Office-to-living potential',
    signalSummary:
      'Trade-press interview: owner of two adjacent 1990s offices "reviewing alternative uses including student and co-living" after a failed re-letting campaign. Desktop check confirms both buildings 60%+ vacant.',
    architecturalIssue:
      'Paired conversion across two buildings with different frame types; shared-core potential, unit-depth testing against daylight, and a policy question on student use outside an opportunity-area boundary.',
    opportunityAngle:
      'The owner has stated intent publicly but has no scheme — a two-building conversion study is a natural first commission and the pair offers economies a single building cannot.',
    relevance: 'Bridges both pilot sectors; SE1 conversion precedents in the portfolio; demonstrates the radar’s office-to-living thesis.',
    nextAction: 'Refresh vacancy data; AO to draft outline study scope before any approach (owner unknown to the practice).',
    status: 'Research',
    scores: {
      sectorFit: 5,
      stageTiming: 3,
      architecturalProblem: 4,
      feePotential: 4,
      relationshipRoute: 2,
      urgency: 2,
    },
    confidence: 40,
    notes: 'Stale — surfaced in May, not reviewed since early June. Either progress the scope draft or move to Dormant at next review.',
    owner: 'AO',
    dateAdded: '2026-05-20',
    lastReviewed: '2026-06-05',
    ai: {
      executiveSummary:
        'A publicly stated but unstructured office-to-living intent across two adjacent SE1 buildings — genuine potential, weak current evidence, and no relationship route yet.',
      classification: 'Manual research — conversion potential, intent stated.',
      likelyIssue: 'Twin-building conversion strategy; daylight-driven unit depths; student-use policy outside the opportunity area.',
      commercialRelevance: 'Conversion feasibility study now; a significant living-sector commission if either building proceeds.',
      recommendedAction: 'Verify vacancy and ownership before investing further; the press signal is now eight weeks old.',
      confidenceNote: 'Low — a single press statement, ageing; no corroborating planning or market activity since.',
      falsePositiveRisk: 'High. "Reviewing alternatives" in trade press is often disposal positioning rather than development intent.',
    },
  },
]

/** RFP monitor rows beyond the two live RFP opportunity cards. */
export const RFP_WATCHLIST: RfpWatchItem[] = [
  {
    id: 'RFP-W-01',
    title: 'LB Camden corporate estate strategy',
    buyer: 'London Borough of Camden',
    sector: 'office-retrofit',
    classification: 'Bid now',
    deadline: '2026-07-24',
    portal: 'ProContract (example)',
    note: 'Quality-weighted 60/40; warm client. Full card on the radar.',
    opportunityId: 'OR-2026-021',
  },
  {
    id: 'RFP-W-02',
    title: 'London Universities housing framework',
    buyer: 'University purchasing consortium',
    sector: 'pbsa-living',
    classification: 'Framework route',
    deadline: '2026-08-14',
    portal: 'Find a Tender (example)',
    note: 'PQQ open; targeting Lots 1 & 3. Full card on the radar.',
    opportunityId: 'PL-2026-020',
  },
  {
    id: 'RFP-W-03',
    title: 'TfL small sites housing programme — design panel refresh',
    buyer: 'Transport for London',
    sector: 'pbsa-living',
    classification: 'Watch buyer',
    portal: 'TfL procurement (example)',
    note: 'Panel refresh signalled for early 2027 in supplier briefing. No action now; calendar checkpoint set for November.',
  },
  {
    id: 'RFP-W-04',
    title: 'White City academic building — design services',
    buyer: 'Imperial College London',
    sector: 'other',
    classification: 'Too late',
    deadline: '2026-06-12',
    portal: 'In-house (example)',
    note: 'ITT closed 12 Jun with an incumbent-heavy shortlist. Log buyer contact for the next capital round.',
  },
  {
    id: 'RFP-W-05',
    title: 'Greystone PBSA design competition — result',
    buyer: 'Greystone Living (private)',
    sector: 'pbsa-living',
    classification: 'Competitor intelligence',
    portal: 'Invited competition',
    note: 'Won by a rival practice with a mass-timber position. Note the winning angle for our next PBSA pursuit.',
  },
  {
    id: 'RFP-W-06',
    title: 'LB Southwark leisure centre retrofit — design services',
    buyer: 'London Borough of Southwark',
    sector: 'other',
    classification: 'Not relevant',
    deadline: '2026-08-03',
    portal: 'ProContract (example)',
    note: 'Outside pilot sectors. Retained on the monitor as buyer intelligence only.',
  },
]

export const ACTIVITY: ActivityEntry[] = [
  { date: '2026-07-08', text: 'Score review: Holloway Road PBSA urgency raised to 5 — appeal deadline confirmed as 12 Aug.', opportunityId: 'PL-2026-006' },
  { date: '2026-07-07', text: 'Added: Fleet House arrival & public realm (internal relationship, JM).', opportunityId: 'OR-2026-022' },
  { date: '2026-07-07', text: 'Added: London Universities housing framework — PQQ deadline 14 Aug.', opportunityId: 'PL-2026-020' },
  { date: '2026-07-06', text: 'Added: LB Camden corporate estate strategy — tender deadline 24 Jul.', opportunityId: 'OR-2026-021' },
  { date: '2026-07-06', text: 'Aldgate House reviewed: pre-app validated on City register; status moved Research → Approach.', opportunityId: 'OR-2026-014' },
  { date: '2026-07-04', text: 'Filmworks North: operator (Habitat & Co) confirmed in amendment planning statement.', opportunityId: 'PL-2026-015' },
  { date: '2026-07-03', text: 'Wick Lane Yard: topo survey activity observed on site; feasibility procurement likely imminent.', opportunityId: 'PL-2026-011' },
  { date: '2026-07-01', text: 'Grafton Quarter reviewed: no design-services notice yet; introduction route via cost consultant identified.', opportunityId: 'OR-2026-019' },
]

/**
 * Schematic borough tile grid (London Squared-style). Positions are
 * approximate-geographic for cluster reading, not a GIS map.
 */
export const BOROUGH_TILES: { name: string; short: string; col: number; row: number }[] = [
  { name: 'Enfield', short: 'ENF', col: 4, row: 0 },
  { name: 'Barnet', short: 'BAR', col: 3, row: 1 },
  { name: 'Haringey', short: 'HGY', col: 4, row: 1 },
  { name: 'Waltham Forest', short: 'WTH', col: 5, row: 1 },
  { name: 'Harrow', short: 'HRW', col: 1, row: 2 },
  { name: 'Brent', short: 'BRT', col: 2, row: 2 },
  { name: 'Camden', short: 'CMD', col: 3, row: 2 },
  { name: 'Islington', short: 'ISL', col: 4, row: 2 },
  { name: 'Hackney', short: 'HCK', col: 5, row: 2 },
  { name: 'Redbridge', short: 'RDB', col: 6, row: 2 },
  { name: 'Havering', short: 'HVG', col: 7, row: 2 },
  { name: 'Hillingdon', short: 'HDN', col: 0, row: 3 },
  { name: 'Ealing', short: 'EAL', col: 1, row: 3 },
  { name: 'Kensington & Chelsea', short: 'KNS', col: 2, row: 3 },
  { name: 'Westminster', short: 'WSM', col: 3, row: 3 },
  { name: 'City of London', short: 'CTY', col: 4, row: 3 },
  { name: 'Tower Hamlets', short: 'TWH', col: 5, row: 3 },
  { name: 'Newham', short: 'NWM', col: 6, row: 3 },
  { name: 'Barking & Dagenham', short: 'BDG', col: 7, row: 3 },
  { name: 'Hounslow', short: 'HNS', col: 0, row: 4 },
  { name: 'Hammersmith & Fulham', short: 'HMS', col: 2, row: 4 },
  { name: 'Lambeth', short: 'LAM', col: 3, row: 4 },
  { name: 'Southwark', short: 'SWK', col: 4, row: 4 },
  { name: 'Lewisham', short: 'LSH', col: 5, row: 4 },
  { name: 'Greenwich', short: 'GRN', col: 6, row: 4 },
  { name: 'Bexley', short: 'BXL', col: 7, row: 4 },
  { name: 'Richmond', short: 'RIC', col: 1, row: 5 },
  { name: 'Wandsworth', short: 'WND', col: 2, row: 5 },
  { name: 'Merton', short: 'MRT', col: 3, row: 5 },
  { name: 'Croydon', short: 'CRY', col: 4, row: 5 },
  { name: 'Bromley', short: 'BRM', col: 5, row: 5 },
  { name: 'Kingston', short: 'KGN', col: 2, row: 6 },
  { name: 'Sutton', short: 'STN', col: 3, row: 6 },
]
